services:
  backend:
    build: backend/
    environment:
      - NEO4J_USER=${DOCKER_NEO4J_USER}
      - NEO4J_PASS=${DOCKER_NEO4J_PASS}
      - NEO4J_URI=bolt://neo4j_db:7687
    ports:
      - "8000:80"
    networks:
      - genealogy_tree_network
    depends_on:
      - neo4j_db
  neo4j_db:
    image: neo4j:5.25.1
    environment:
      - NEO4J_AUTH=${DOCKER_NEO4J_USER}/${DOCKER_NEO4J_PASS}
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/init.cypher:/var/lib/neo4j/import/init.cypher
      - ./neo4j/data:/data
    networks:
      - genealogy_tree_network

networks:
  genealogy_tree_network:
    driver: bridge
