services:
  backend:
    build: backend/
    environment:
      - NEO4J_USER=${DOCKER_NEO4J_USER}
      - NEO4J_PASS=${DOCKER_NEO4J_PASS}
      - NEO4J_URI=bolt://neo4j_db:7687
      - NEO4J_DB_NAME=neo4j
    volumes:
      - "./backend:/app"
    ports:
      - "8000:80"
    networks:
      - genealogy_tree_network
    depends_on:
      - neo4j_db
  neo4j_db:
    build: neo4j/
    env_file:
      - path: ./.env
        required: true
    environment:
      - NEO4J_AUTH=${DOCKER_NEO4J_USER}/${DOCKER_NEO4J_PASS}
    volumes:
      - "./neo4j/data:/data"
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - genealogy_tree_network

networks:
  genealogy_tree_network:
    driver: bridge
